---
apiVersion: v1
kind: Pod
metadata:
  name: pytest
  labels:
    # atop.io/enable: "true"
    atop.io/app: pytest
    atop.io/managed-by: core
  annotations:
    atop.io/report-path: /demo/report
    atop.io/protocol: s3
spec:
  restartPolicy: Never
  containers:
    - name: pytest
      image: no8ge/demo:1.0.0
      args:
        - /bin/sh
        - -c
        - pytest --html=report/report.html -s -v;sleep 60
      ports:
        - containerPort: 8002
      env:
        - name: HOST
          value: "demo.default.svc:8002"
