---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    atop.io/app: pytest
    atop.io/managed-by: core
  annotations:
    atop.io/report-path: /demo/report
    atop.io/protocol: s3
spec:
  restartPolicy: Never
  containers:
    - name: pytest
      image: no8ge/demo:1.0.0
      args:
        - /bin/sh
        - -c
        - pytest --html=report/report.html -s -v;sleep 60
      ports:
        - containerPort: 9000
      env:
        - name: HOST
          value: "demo.default.svc:8002"
      volumeMounts:
        - name: cache-volume
          mountPath: /demo/report
    - name: sidecar
      image: no8ge/sidecar:20240218174958-f1530be
      command: ["sh", "-c", "./sidecar watch -d /data -p $HOSTNAME -b test"]
      ports:
        - containerPort: 8080      
      volumeMounts:
        - name: cache-volume
          mountPath: /data
  volumes:
    - name: cache-volume
      emptyDir: {}
